[build]
  command = "npm run build:export"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Ensure static HTML files are served correctly
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "text/html; charset=utf-8"

# Ensure proper redirects and headers for static files
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

# Ensure proper caching for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Ensure proper caching for images
[[headers]]
  for = "/og-images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Handle static files with query parameters
# Redirect routes with query parameters to their static equivalents
[[redirects]]
  from = "/blog/:slug"
  to = "/blog/:slug.html"
  status = 200
  force = false

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200
  force = false

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = false